### ISSUE TITLE
Problem Opening

### ISSUE THREAD

**Issue by Blazedude77** [TerrariaPrismTeam/Prism#22]
So I opened Prism for the first time and got this message:

A fatal error occured:
System.TypeInitializationException: The type initializer for
'Terraria.Main' threw an exception. ---> System.NullReferenceException:
Object reference not set to an instance of an object.
   at Terraria.NPC.RealSetDefaults(Int32 Type, Single scaleOverride)
   at Terraria.NPC.SetDefaults(Int32 Type, Single scaleOverride)
   at Terraria.NPC.RealSetDefaults(String Name)
   at Terraria.Item.SetDefaults(String ItemName
   at Terraria.Player..ctor()
   at Terraria.Main..ctor() in C:\Users\Pieter\Documents\Visual Studio
2015\Projects\Prism\Prism\PrismLauncher.cs:line 87
   at Prism.Program.Main(string[] args)in C:\Users\Pieter\Documents\Visual Studio
2015\Projects\Prism\Prism\Program.cs:line 35

did i do something wrong? i thought i followed all of the steps... maybe it's a glitch. please RASAP

**Comment by PoroCYon** [comment]
Are you trying to use it with Terraria 1.3.2? Prism is not compatible with it yet.

**Comment by Blazedude77** [comment]
@PoroCYon ok thanks. can you notify me when it supports 1.3.2?

EDIT: or is there any way to open it to 1.3.1?

**Comment by PoroCYon** [comment]
It [is binary compatible with 1.3.2.1 now](https://github.com/TerrariaPrismTeam/Prism/commit/acc45dac18e0d4f3a6f2710d240891e05b8ed49f), The last 1.3.1 commit can be found [here](https://github.com/TerrariaPrismTeam/Prism/commit/815272d632de06f805df5a668cc44a0897c855ff). These aren't added to the release page yet, though.
